import math

# Servos
ARM_PORT = 0
WRIST_PORT = 1
CLAW_PORT = 2 
MINI_PORT = 3

# Motor_Servo
DROPPER_PORT = 1
    
# Sensors
RANGEFINDER = "rangefinder"
RANGEFINDER_PORT = 1

# 3 MAX - 900

# Servos General Constants

ARM_STARTING_POSITION = 180
WRIST_STARTING_POSITION = 1650
CLAW_STARTING_POSITION = 150
MINI_PORT = 550

CLAW_OPEN_POSITION = 700
CLAW_CLOSED_POSITION = 1900

ARM_DRIVE_POSITION = 1850
WRIST_DRIVE_POSITION = 1800

# Servos with Botgal Constants

ARM_GRAB_POSITION_TOP = 1790
WRIST_GRAB_POSITION_TOP = 120

ARM_BOTGAL_RAISE_POSITION = 1900
WRIST_BOTGAL_RAISE_POSITION = 440

ARM_BOTGAL_LOWER_POSITION = 700
WRIST_BOTGAL_LOWER_POSITION = 1250

ARM_BOTGAL_DROP_POSITION = 350
WRIST_BOTGAL_DROP_POSITION = 1500

# Servos with Cube Constants

ARM_CUBE_RAISE_POSITION = 1900
WRIST_CUBE_RAISE_POSITION = 440

ARM_CUBE_LOWER_POSITION = 700
WRIST_CUBE_LOWER_POSITION = 1250

ARM_GRAB_CUBE_POSITION_TOP = 1750
WRIST_GRAB_CUBE_POSITION_TOP = 150

ARM_GRAB_CUBE_POSITION_BOTTOM = 930
WRIST_GRAB_CUBE_POSITION_BOTTOM = 1000

WRIST_GRAB_CUBE_POSITION_EXTEND = 770

ARM_CUBE_POSITION_DROP_1 = 350
WRIST_CUBE_POSITION_DROP_1 = 1500
BACKUP_DISTANCE_1 = 0
    
ARM_CUBE_POSITION_DROP_2 = 550
WRIST_CUBE_POSITION_DROP_2 = 1500
BACKUP_DISTANCE_2 = 6

ARM_CUBE_POSITION_DROP_3 = 1000
WRIST_CUBE_POSITION_DROP_3 = 850
BACKUP_DISTANCE_3 = 10

ARM_CUBE_POSITION_DROP_4 = 1230
WRIST_CUBE_POSITION_DROP_4 = 800
BACKUP_DISTANCE_4 = 12

#ARM_GRAB_POSITION_SECOND = 1250
#WRIST_GRAB_POSITION_SECOND = 1900
    
# Rings to PVC 
    
ARM_RING_POSITION = 900
CLAW_RING_POSITION = 1900

SERVO_INCREMENT = {ARM_PORT: 5, WRIST_PORT: 5, CLAW_PORT: 5}
SERVO_INCREMENT_FAST = {ARM_PORT: 8, WRIST_PORT: 8, CLAW_PORT: 8}
SERVO_SLEEP_TIME = 5
    
# Sensors

# Drive
MAX_SPEED = 500
DRIVE_SPEED = 250
TURN_SPEED = 150

# Line following (1850 is correct value)
LINE_FOLLOW_TARGET = 1850 #2200 #1250
LINE_FOLLOW_BASE_SPEED = 200
    
KP = 0.05
KI = 0.0005
KD = 0.00005

KP_drive = 2.5 #5
KI_drive = 0
KD_drive = 40

KP_drive_angle = 5
KI_drive_angle = 0
KD_drive_angle = 40

WHEEL_SPAN = 235.0
WHEEL_DIAMETER = 72.0
TICK_PER_REVOLUTION = 508.8
TICK_PER_MM = TICK_PER_REVOLUTION/(math.pi*WHEEL_DIAMETER)

MIN_ENCODER_VAL = -32768
MAX_ENCODER_VAL = 32767
# Distances/Board Constants
HORIZONTAL_BOTGAL_ALIGNMENT_DISTANCE = 7
BOTGAL_FORWARD_DROP_DISTANCE = 20

RIGHT_TALL_TOWER_HORIZONTAL_DISTANCE = 45
RIGHT_TALL_TOWER_VERTICAL_DISTANCE = 37.5 - 10
RIGHT_TALL_TOWER_ALIGNMENT_DISTANCE = 25

LEFT_TALL_TOWER_HORIZONTAL_DISTANCE = 48
LEFT_TALL_TOWER_VERTICAL_DISTANCE = 37.5 - 10
LEFT_TALL_TOWER_ALIGNMENT_DISTANCE = 25

LEFT_SHORT_TOWER_HORIZONTAL_DISTANCE = 92
LEFT_SHORT_TOWER_VERTICAL_DISTANCE = 27.5 - 10
LEFT_SHORT_TOWER_ALIGNMENT_DISTANCE = 25 - BACKUP_DISTANCE_2

RIGHT_SHORT_TOWER_HORIZONTAL_DISTANCE = 82
RIGHT_SHORT_TOWER_VERTICAL_DISTANCE = 30 - 10
RIGHT_SHORT_TOWER_ALIGNMENT_DISTANCE = 25 - BACKUP_DISTANCE_3