import math

# Servos
ELBOW_PORT = 1
WRIST_PORT = 0
    
# Mini Servos
CLAW_PORT = 2 

# Motor_Servo
DROPPER_PORT = 1

# 3 MAX - 900

# Servos General Constants
    
    
#ELBOW POS B/W 250 and 1550 (VATSAL'S SAT SCORE)

ELBOW_STARTING_POSITION = 250
    
#WRIST POS B/W 400 and 1450
WRIST_STARTING_POSITION = 1650
CLAW_STARTING_POSITION = 150

CLAW_OPEN_POSITION = 700
CLAW_CLOSED_POSITION = 1900

ARM_DRIVE_POSITION = 1850
WRIST_DRIVE_POSITION = 1800

#Square Servo Positions
BASE_DOWN_SQUARE_POSITION = 1950


###############################
ARM_CUBE_RAISE_POSITION = 1900
WRIST_CUBE_RAISE_POSITION = 440

ARM_CUBE_LOWER_POSITION = 700
WRIST_CUBE_LOWER_POSITION = 1250

ARM_GRAB_CUBE_POSITION_TOP = 1750
WRIST_GRAB_CUBE_POSITION_TOP = 150

ARM_GRAB_CUBE_POSITION_BOTTOM = 980
WRIST_GRAB_CUBE_POSITION_BOTTOM = 1000


#ARM_GRAB_POSITION_SECOND = 1250
#WRIST_GRAB_POSITION_SECOND = 1900
    
# Rings to PVC 
    
ARM_RING_POSITION = 900
CLAW_RING_POSITION = 1900


SERVO_SLEEP_TIME = 5
    
# Sensors

# Drive
MAX_SPEED = 500
DRIVE_SPEED = 250
TURN_SPEED = 150

# Line following (1850 is correct value)
LINE_FOLLOW_TARGET = 1850 #2200 #1250
LINE_FOLLOW_BASE_SPEED = 200
    
KP = 0.05
KI = 0.0005
KD = 0.00005

KP_drive = 5
KI_drive = 0
KD_drive = 40

KP_drive_angle = 5
KI_drive_angle = 0
KD_drive_angle = 40

WHEEL_SPAN = 235.0
WHEEL_DIAMETER = 72.0
TICK_PER_REVOLUTION = 508.8
TICK_PER_MM = TICK_PER_REVOLUTION/(math.pi*WHEEL_DIAMETER)

MIN_ENCODER_VAL = -32768
MAX_ENCODER_VAL = 32767
# Distances/Board Constants
HORIZONTAL_BOTGAL_ALIGNMENT_DISTANCE = 7
BOTGAL_FORWARD_DROP_DISTANCE = 20

RIGHT_TALL_TOWER_HORIZONTAL_DISTANCE = 45
RIGHT_TALL_TOWER_VERTICAL_DISTANCE = 40
RIGHT_TALL_TOWER_ALIGNMENT_DISTANCE = 25

LEFT_TALL_TOWER_HORIZONTAL_DISTANCE = 40
LEFT_TALL_TOWER_VERTICAL_DISTANCE = 35
LEFT_TALL_TOWER_ALIGNMENT_DISTANCE = 25

LEFT_SHORT_TOWER_HORIZONTAL_DISTANCE = 92
LEFT_SHORT_TOWER_VERTICAL_DISTANCE = 25
#LEFT_SHORT_TOWER_ALIGNMENT_DISTANCE = 25 - BACKUP_DISTANCE_2

RIGHT_SHORT_TOWER_HORIZONTAL_DISTANCE = 84
RIGHT_SHORT_TOWER_VERTICAL_DISTANCE = 30
#RIGHT_SHORT_TOWER_ALIGNMENT_DISTANCE = 25 - BACKUP_DISTANCE_3